# Q.1 Write a python program to demonstrate the use of LIST with appropriate method

In [4]:
# Creating a list
fruits = ['apple', 'banana', 'orange', 'grape']

# 1. Accessing elements of the list
print("First fruit:", fruits[0])
print("Last fruit:", fruits[-1])

# 2. Adding elements to the list
fruits.append('kiwi')
print("Fruits after adding 'kiwi':", fruits)

# 3. Removing elements from the list
removed_fruit = fruits.pop(2)
print("Removed fruit:", removed_fruit)
print("Fruits after removing the third fruit:", fruits)

# 4. Modifying elements of the list
fruits[1] = 'pineapple'
print("Fruits after replacing 'banana' with 'pineapple':", fruits)

# 5. Sorting the list
fruits.sort()
print("Fruits after sorting:", fruits)

# 6. Reversing the list
fruits.reverse()
print("Fruits after reversing:", fruits)

# 7. Finding the index of an element
index = fruits.index('apple')
print("Index of 'apple':", index)

# 8. Counting occurrences of an element
count = fruits.count('orange')
print("Number of 'orange' in the list:", count)

# 9. Slicing the list
print("First three fruits:", fruits[:3])

# 10. Clearing the list
fruits.clear()
print("Fruits list after clearing:", fruits)


First fruit: apple
Last fruit: grape
Fruits after adding 'kiwi': ['apple', 'banana', 'orange', 'grape', 'kiwi']
Removed fruit: orange
Fruits after removing the third fruit: ['apple', 'banana', 'grape', 'kiwi']
Fruits after replacing 'banana' with 'pineapple': ['apple', 'pineapple', 'grape', 'kiwi']
Fruits after sorting: ['apple', 'grape', 'kiwi', 'pineapple']
Fruits after reversing: ['pineapple', 'kiwi', 'grape', 'apple']
Index of 'apple': 3
Number of 'orange' in the list: 0
First three fruits: ['pineapple', 'kiwi', 'grape']
Fruits list after clearing: []


# Q.2 Write a python program to demonstrate the use of SET with appropriate method

In [5]:
# Creating a set
fruits = {"apple", "banana", "orange", "grape", "banana"}

# Displaying the original set
print("Original set of fruits:", fruits)

# Adding an element to the set
fruits.add("pineapple")
print("After adding 'pineapple':", fruits)

# Removing an element from the set
fruits.remove("banana")
print("After removing 'banana':", fruits)

# Checking if an element exists in the set
print("Is 'apple' in the set?", "apple" in fruits)

# Iterating over the set
print("Fruits in the set:")
for fruit in fruits:
    print(fruit)

# Getting the length of the set
print("Number of fruits in the set:", len(fruits))

# Creating another set
more_fruits = {"kiwi", "melon", "orange", "grape"}

# Performing set operations
print("Intersection of the two sets:", fruits.intersection(more_fruits))
print("Union of the two sets:", fruits.union(more_fruits))
print("Difference between the two sets:", fruits.difference(more_fruits))
print("Symmetric difference between the two sets:", fruits.symmetric_difference(more_fruits))

# Clearing the set
fruits.clear()
print("After clearing the set:", fruits)


Original set of fruits: {'grape', 'apple', 'banana', 'orange'}
After adding 'pineapple': {'grape', 'banana', 'pineapple', 'apple', 'orange'}
After removing 'banana': {'grape', 'pineapple', 'apple', 'orange'}
Is 'apple' in the set? True
Fruits in the set:
grape
pineapple
apple
orange
Number of fruits in the set: 4
Intersection of the two sets: {'grape', 'orange'}
Union of the two sets: {'grape', 'kiwi', 'pineapple', 'apple', 'melon', 'orange'}
Difference between the two sets: {'pineapple', 'apple'}
Symmetric difference between the two sets: {'kiwi', 'pineapple', 'apple', 'melon'}
After clearing the set: set()


# Q.3 Write a python program to demonstrate the use of DICTIONARY with appropriate method

In [6]:
# Creating a dictionary
student_scores = {
    "Alice": 85,
    "Bob": 72,
    "Charlie": 90,
    "David": 68,
    "Eve": 95
}

# Accessing values using keys
print("Alice's score:", student_scores["Alice"])

# Adding a new key-value pair
student_scores["Frank"] = 80
print("Added Frank's score:", student_scores)

# Modifying a value
student_scores["Bob"] = 75
print("Bob's updated score:", student_scores)

# Removing a key-value pair
del student_scores["David"]
print("Dictionary after removing David:", student_scores)

# Checking if a key exists
if "Alice" in student_scores:
    print("Alice's score:", student_scores["Alice"])

# Iterating through keys
print("Students and their scores:")
for student in student_scores:
    print(student, ":", student_scores[student])

# Iterating through keys and values
print("Students and their scores:")
for student, score in student_scores.items():
    print(student, ":", score)

# Getting the length of the dictionary
print("Number of students:", len(student_scores))

# Clearing the dictionary
student_scores.clear()
print("Cleared dictionary:", student_scores)


Alice's score: 85
Added Frank's score: {'Alice': 85, 'Bob': 72, 'Charlie': 90, 'David': 68, 'Eve': 95, 'Frank': 80}
Bob's updated score: {'Alice': 85, 'Bob': 75, 'Charlie': 90, 'David': 68, 'Eve': 95, 'Frank': 80}
Dictionary after removing David: {'Alice': 85, 'Bob': 75, 'Charlie': 90, 'Eve': 95, 'Frank': 80}
Alice's score: 85
Students and their scores:
Alice : 85
Bob : 75
Charlie : 90
Eve : 95
Frank : 80
Students and their scores:
Alice : 85
Bob : 75
Charlie : 90
Eve : 95
Frank : 80
Number of students: 5
Cleared dictionary: {}


# Q.4 Write a python program to demonstrate the use of TUPLE with appropriate method

In [7]:
# Define a tuple
my_tuple = (1, 2, 3, 4, 5)

# Accessing elements of a tuple
print("Tuple elements:", my_tuple)
print("First element:", my_tuple[0])
print("Last element:", my_tuple[-1])

# Tuple slicing
print("Sliced tuple:", my_tuple[1:4])

# Tuple length
print("Length of tuple:", len(my_tuple))

# Counting occurrences of an element in a tuple
print("Count of '3' in tuple:", my_tuple.count(3))

# Finding index of an element in a tuple
print("Index of '4' in tuple:", my_tuple.index(4))

# Converting a tuple to a list
tuple_list = list(my_tuple)
print("Tuple converted to list:", tuple_list)

# Concatenating tuples
another_tuple = (6, 7, 8)
concatenated_tuple = my_tuple + another_tuple
print("Concatenated tuple:", concatenated_tuple)


Tuple elements: (1, 2, 3, 4, 5)
First element: 1
Last element: 5
Sliced tuple: (2, 3, 4)
Length of tuple: 5
Count of '3' in tuple: 1
Index of '4' in tuple: 3
Tuple converted to list: [1, 2, 3, 4, 5]
Concatenated tuple: (1, 2, 3, 4, 5, 6, 7, 8)


# Q.5 Write a python program to demonstrate the use of NUMPY library

In [8]:
import numpy as np

# Creating a 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)

# Creating a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2d)

# Array shape
print("\nShape of 1D Array:", arr1d.shape)
print("Shape of 2D Array:", arr2d.shape)

# Accessing elements
print("\nAccessing elements:")
print("First element of 1D Array:", arr1d[0])
print("Element at row 1, column 2 of 2D Array:", arr2d[0, 1])

# Array operations
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print("\nArray operations:")
print("Sum of arrays:")
print(arr1 + arr2)
print("Element-wise multiplication of arrays:")
print(arr1 * arr2)
print("Matrix multiplication of arrays:")
print(np.dot(arr1, arr2))


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Shape of 1D Array: (5,)
Shape of 2D Array: (2, 3)

Accessing elements:
First element of 1D Array: 1
Element at row 1, column 2 of 2D Array: 2

Array operations:
Sum of arrays:
[[ 6  8]
 [10 12]]
Element-wise multiplication of arrays:
[[ 5 12]
 [21 32]]
Matrix multiplication of arrays:
[[19 22]
 [43 50]]


# Q.6 write a python prg to demonstrate the use of function each function should contain one looping type

In [9]:
def while_loop_example():
    # Function to demonstrate while loop
    num = 1
    while num <= 5:
        print(num)
        num += 1

def for_loop_example():
    # Function to demonstrate for loop
    for i in range(1, 6):
        print(i)

def nested_loop_example():
    # Function to demonstrate nested loop
    for i in range(1, 4):
        for j in range(1, 4):
            print(f'({i}, {j})')

def do_while_loop_example():
    # Function to demonstrate do-while loop (Python doesn't have a built-in do-while loop,
    # but similar behavior can be achieved with a while loop)
    num = 1
    while True:
        print(num)
        num += 1
        if num > 5:
            break

# Call each function to demonstrate the loop type
print("While Loop Example:")
while_loop_example()
print("\nFor Loop Example:")
for_loop_example()
print("\nNested Loop Example:")
nested_loop_example()
print("\nDo-While Loop Example:")
do_while_loop_example()


While Loop Example:
1
2
3
4
5

For Loop Example:
1
2
3
4
5

Nested Loop Example:
(1, 1)
(1, 2)
(1, 3)
(2, 1)
(2, 2)
(2, 3)
(3, 1)
(3, 2)
(3, 3)

Do-While Loop Example:
1
2
3
4
5


# Q.7 write a python prg to demonstrate the use of various Date function

In [10]:
import datetime

def current_date():
    # Function to get the current date
    current_date = datetime.date.today()
    print("Current Date:", current_date)

def date_operations():
    # Function to demonstrate date operations
    today = datetime.date.today()
    future_date = today + datetime.timedelta(days=30)
    print("Today's Date:", today)
    print("Date after 30 days:", future_date)

def date_formatting():
    # Function to demonstrate date formatting
    today = datetime.date.today()
    formatted_date = today.strftime("%d-%m-%Y")
    print("Formatted Date:", formatted_date)

def custom_date():
    # Function to create a custom date
    custom_date = datetime.date(2024, 4, 22)
    print("Custom Date:", custom_date)

# Call each function to demonstrate various date functions
print("Current Date:")
current_date()
print("\nDate Operations:")
date_operations()
print("\nDate Formatting:")
date_formatting()
print("\nCustom Date:")
custom_date()


Current Date:
Current Date: 2024-04-22

Date Operations:
Today's Date: 2024-04-22
Date after 30 days: 2024-05-22

Date Formatting:
Formatted Date: 22-04-2024

Custom Date:
Custom Date: 2024-04-22
